#!/usr/bin/env bash

# Function to calculate the product of factors
calculate_product() {
    local product_result=1
    local first_num="$2"
    local second_num=$(echo "$1" | tr ':' '=')

    for arg in "${@:3}"; do
        product_result=$((product_result * arg))
    done

    if ((product_result > first_num)); then
        local temp_num="$first_num"
        first_num="$product_result"
        product_result="$temp_num"
    fi

    echo "$second_num$first_num*$product_result"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r input_line; do
        result=($(factor "$input_line"))
        calculate_product "${result[@]}"
    done < "$1"
fi
