#!/usr/bin/env bash

# Function to calculate the product of factors
calculate_product() {
    if [ $# -ne 3 ]; then
	return
    else
        local product_result="$3"
    fi

    local first_num="$2"
    local second_num=$(echo "$1" | tr ':' '=')

    local comparison_result=$(echo "if ($product_result > $first_num) 1 else 0" | bc)

    if ((comparison_result == 1)); then
        local temp_num="$first_num"
        first_num="$product_result"
        product_result="$temp_num"
    fi

    echo "$second_num$first_num*$product_result"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read file_line; do
        result=$(factor "$file_line")
        calculate_product $result
    done < "$1"
fi
